%function plot_aam_ann_cycle_compare(comp,compgeo)
% Comparing the monthly mean AAM terms in EMAC output for different 
% datasets
%
% INPUTS:
% 	comp: which component -- choose 1, 2, or 3.
%	compgeo: set to 1 in order to just compare CCMVal and ERA to GEO
%
% MODS:
%  2 Mar 2011: fixed messed up plot labels.
%  2 Mar 2011: added ERA-Interim result for comparison.


%---specify AAM monthly mean data fiels and run names
%   (data files generated by aam_emac_volint_mm.m)

if compgeo
  R = [4:6,10];
else
  R = [1:4,6,10];
end
nR = length(R);

[runs,names,ef,no_ib] = aam_paper_runs;
nf = length(runs);

%---load constants and compute AAM prefactors

aam_constants_gross
Re = Re_m;	% (use earth radius in meters)

% new form (Gross 09)
pm12 = -1.608*0.684*Re^4/(g*(C-A));
pw12 = -1.608*Re^3/(Q*g*(C-A));
pm3  = 0.997*0.750*Re^4/(g*Cm);
pw3  = 0.997*Re^3/(Q*g*Cm);
pm = [pm12; pm12; pm3];
pw = [pw12; pw12; pw3];

% cycle through files, load data, store interannual means.
X = zeros(nf,3,3,12)+NaN;
dX = zeros(nf,3,3,12)+NaN;
nyears = zeros(nf,1);
nmonths = zeros(nf,1);

for irun = R
  runid = runs(irun);

  sdir = ['/dsk/nathan/lisa/ex/',char(runid),'/mat/'];
  ff = dir([sdir,'aam_vol_mm_*.mat']);
  fname = [sdir,ff.name];
  if exist(fname)==2, load(fname), else disp(['cant find mat file for ' char(runid)]), end


  %---compute the long term mean of both X arrays and subtract out
  ny = size(Xm_mm,3);
  nm = size(Xm_mm,2);
  nyears(irun) = ny;
  nmonths(irun) = nm;

  Xm_anom = Xm_mm*0;
  Xw_anom = Xw_mm*0;
  Xm_LT = zeros(3,1);
  Xw_LT = zeros(3,1);

  % long-term mean: average over all months and all years.
  Xm_LT = nanmean(nanmean(Xm_mm(:,:,:),3),2);
  Xw_LT = nanmean(nanmean(Xw_mm(:,:,:),3),2);

  % compute anomaly wrt LT mean, and mult by prefactors 
  for im = 1:nm
    for iy = 1:ny
      Xm_anom(:,im,iy) = pm.*(Xm_mm(:,im,iy) - Xm_LT);
      Xw_anom(:,im,iy) = pw.*(Xw_mm(:,im,iy) - Xw_LT);
    end
  end
 
  % convert to mas for X1 and X2, ms for X3
  Xm = Xm_mm*0+NaN;
  Xw = Xm_mm*0+NaN;
  Xm(1:2,:,:) = rad2mas*Xm_anom(1:2,:,:);
  Xw(1:2,:,:) = rad2mas*Xw_anom(1:2,:,:);
  Xm(3,:,:) = LOD0_ms*Xm_anom(3,:,:);
  Xw(3,:,:) = LOD0_ms*Xw_anom(3,:,:);

  % now compute interannual mean, standard deviation, etc
  Xmear =  zeros(2,3,nm);
  Xstd =  zeros(2,3,nm);
  flag = 0;	% (for std, use N-1 normalization)
  Xmean(1,:,:) = nanmean(Xw,3); 
  Xmean(2,:,:) = nanmean(Xm,3); 
  Xstd(1,:,:) = nanstd(Xw,flag,3);
  Xstd(2,:,:) = nanstd(Xm,flag,3);

  % fill in the mean terms, etc
  X(irun,1:2,:,:) = Xmean;
  X(irun,3,:,:) = sum(Xmean,1);
  dX(irun,1:2,:,:) = Xstd;
  dX(irun,3,:,:) = sqrt(sum(Xstd.^2,1));

end

%---also compute the monthly mean excitations from ERAinterim
irun = 5;
[Xw_mm_era,Xm_mm_era,Y] = aam_era_mm('aam');

X(irun,1,:,:) = mean(Xw_mm_era,3);
X(irun,2,:,:) = mean(Xm_mm_era,3);
X(irun,3,:,:) = mean(Xw_mm_era,3)+mean(Xm_mm_era,3);
dX(irun,1,:,:) = std(Xw_mm_era,flag,3);
dX(irun,2,:,:) = std(Xm_mm_era,flag,3);
dX(irun,3,:,:) = sqrt((std(Xw_mm_era,flag,3)).^2+(std(Xm_mm_era,flag,3)).^2);

%---also add the monthly mean excitations implied by geodetic data.
% (only add to the total)
% here subtract out OAM and HAM contributions.
irun = 6;
[X_mm_geo,Y] = aam_geo_mm;
[Xw_mm_oam,Xm_mm_oam,Y] = aam_era_mm('oam');
[Xw_mm_ham,Xm_mm_ham,Y] = aam_era_mm('ham');
X_mm_oam = Xw_mm_oam+Xm_mm_oam;
X_mm_ham = Xw_mm_ham+Xm_mm_ham;

% Before averaging, remove the mean from each year, 
% so that the long term variation of EOPs 
% (presumably due to core-mantle coupling) is removed.
% (see notes vol. 4, p. 18)
X_mm_geo_dt = X_mm_geo*0+NaN;		X_mm_oam_dt = X_mm_oam*0+NaN;		X_mm_ham_dt = X_mm_ham*0+NaN;	
for ii = 1:3
  for iy = 1:size(X_mm_geo,3), X_mm_geo_dt(ii,:,iy) = detrend(X_mm_geo(ii,:,iy),'constant'); end
  for iy = 1:size(X_mm_oam,3), X_mm_oam_dt(ii,:,iy) = detrend(X_mm_oam(ii,:,iy),'constant'); end
  for iy = 1:size(X_mm_ham,3), X_mm_ham_dt(ii,:,iy) = detrend(X_mm_ham(ii,:,iy),'constant'); end
end

X_geo = mean(X_mm_geo_dt,3);
dX_geo = std(X_mm_geo_dt,flag,3);
X_oam = mean(X_mm_oam_dt,3);
dX_oam = std(X_mm_oam_dt,flag,3);
X_ham = mean(X_mm_ham_dt,3);
dX_ham = std(X_mm_ham_dt,flag,3);

X_net = X_geo-X_oam-X_ham;
dX_net = sqrt( dX_geo.^2 + dX_oam.^2 + dX_ham.^2 );
X(irun,3,:,:) = X_net;
dX(irun,3,:,:) = dX_net;

%--plot settings

LW = 3;
ifig = 1;
TTw = {'\chi_1 Wind Term','\chi_2 Wind Term','\Delta LOD Wind Term'};
TTm = {'\chi_1 Mass Term','\chi_2 Mass Term','\Delta LOD Mass Term'};
TTt = {'\chi_1 Total','\chi_2 Total','\Delta LOD Total'};

TT = [TTw; TTm; TTt];

col_big = aam_paper_colors;
col = col_big(R,:);

transparency = 0.3;

lh = zeros(nf,1);

ax = zeros(3,2);
ax(1,:) = 25*[-1,1];	% range for X1 in mas
ax(2,:) = 60*[-1,1];	% range for X2 in mas
ax(3,:) = 0.8*[-1,1];	% range for DLOD in ms

% set option of which runs to show here:
if compgeo
  runs_to_show_here = [6,5,4];	% comparison to geodetic obs
  terms_to_show = [1,2,3];		% show total only when we compare to geo.
else
  runs_to_show_here = [1,2,3,4,5];
  terms_to_show = [1,2,3];		% show total only when we compare to geo.
end
names_short = names(runs_to_show_here);

%--- make plots!


for term = terms_to_show	% loop over terms: wind, pressure, total (or just total)
  figure(term),clf
    for irun = runs_to_show_here
      x = squeeze(X(irun,term,comp,:))';
      dx = squeeze(dX(irun,term,comp,:))';
      lh(irun) = plot(1:12,x,'Color',col(irun,:),'LineWidth',LW);
      [h,msg] = jbfill(1:12,x+dx,x-dx,col(irun,:),ones(1,3),1,transparency);
      hold on
    end

    title(TT(term,comp))
    axis([0 12 ax(comp,:)]);
    xlabel('Month')
    if comp < 3, ylabel('mas'), else ylabel('ms'), end
    legend(lh(runs_to_show_here),names_short,'Location','SouthOutside','Orientation','Horizontal')
    legend('BoxOff')
    set(gca,'LineWidth',3.0)
end

plot_dir = '/home/ig/neef/Documents/Plots/aam_run_comparison/';
if compgeo
  fig_name_w = [plot_dir,'comp_ann_cycle_X',num2str(comp),'w_geo.eps'];
  fig_name_m = [plot_dir,'comp_ann_cycle_X',num2str(comp),'m_geo.eps'];
  fig_name_t = [plot_dir,'comp_ann_cycle_X',num2str(comp),'_geo.eps'];
  fig_name_w2 = [plot_dir,'comp_ann_cycle_X',num2str(comp),'w_geo.png'];
  fig_name_m2 = [plot_dir,'comp_ann_cycle_X',num2str(comp),'m_geo.png'];
  fig_name_t2 = [plot_dir,'comp_ann_cycle_X',num2str(comp),'_geo.png'];
else
  fig_name_w = [plot_dir,'comp_ann_cycle_X',num2str(comp),'w.eps'];
  fig_name_m = [plot_dir,'comp_ann_cycle_X',num2str(comp),'m.eps'];
  fig_name_t = [plot_dir,'comp_ann_cycle_X',num2str(comp),'.eps'];
  fig_name_w2 = [plot_dir,'comp_ann_cycle_X',num2str(comp),'w.png'];
  fig_name_m2 = [plot_dir,'comp_ann_cycle_X',num2str(comp),'m.png'];
  fig_name_t2 = [plot_dir,'comp_ann_cycle_X',num2str(comp),'.png'];
end

rend = 'opengl';

LW = 4;
ph = 8;	% paper height
pw = 10;	% paper width
fs = 30;	% fontsize

exportfig(1,fig_name_w2,'width',pw,'height',ph,'fontmode','fixed', 'fontsize',fs,'color','cmyk','renderer',rend,'LineMode','fixed','LineWidth',LW,'format','png');
exportfig(2,fig_name_m2,'width',pw,'height',ph,'fontmode','fixed', 'fontsize',fs,'color','cmyk','renderer',rend,'LineMode','fixed','LineWidth',LW,'format','png');
exportfig(3,fig_name_t2,'width',pw,'height',ph,'fontmode','fixed', 'fontsize',fs,'color','cmyk','renderer',rend,'LineMode','fixed','LineWidth',LW,'format','png');




