% Comparing the monthly mean AAM terms in EMAC output.
% We want to see what the annual cycle looks like for each term and then compare that
% to how the components change regionally.
% The overlying goal is to see what regions most influence a certain timescale of variation.


clear all;

%---load data processed from an EMAC run
%   (data file generated by aam_emac_volint_mm.m)
load aam_vol_mm_doubleCO2_T42L39.mat
%load aam_vol_mm_t7_T42L39.mat
%load aam_vol_mm_ccmval.mat

%---constants and conversions
d2r = pi/180.;         %  degrees to radian
rlat = lat*d2r;
rlon = lon*d2r;

Re = 6.371e6;           % radius of earth in meters
Q = 7.292115e-5;        % rotation rate of the earth in rad/s
g = 9.81;               % grav constant in m/s2
C = 7.1236e37;          % principal moment of inertia of the mantle in kgm2
CminusA = 2.34e35;       % C minus eq. MOI, same units
d2r = pi/180.;         %  degrees to radian

pm12 = -Re^4/(g*CminusA);
pw12 = -1.43*Re^3/(Q*g*CminusA);
pm3  = 0.7*Re^4/(g*C);
pw3  = Re^3/(Q*g*C);

rad2microas = (180/pi)*60*60*1e6;
rad2mas = (180/pi)*60*60*1e3;

LOD0 = double(24*60*60*1e3);            % standard LOD in milliseconds.

nyears = size(Xm_mm,3);
nm = size(Xm_mm,2);

%---compute the long term mean of both X arrays and subtract out

Xm_mm_anom = Xm_mm*0;
Xw_mm_anom = Xw_mm*0;

Xm_LT = zeros(3,1);
Xw_LT = zeros(3,1);

for im = 1:nm
  dum_m = squeeze(Xm_mm(1,im,:));
  dum_w = squeeze(Xw_mm(1,im,:));
  good_years_m = find(isfinite(dum_m) == 1);
  good_years_w = find(isfinite(dum_w) == 1);
  Xm_LT = Xm_LT + (1/nm)*mean(Xm_mm(:,im,good_years_m),3);
  Xw_LT = Xw_LT + (1/nm)*mean(Xw_mm(:,im,good_years_w),3);
end

for im = 1:nm
  for iy = 1:nyears
    Xm_mm_anom(:,im,iy) = Xm_mm(:,im,iy) - Xm_LT;
    Xw_mm_anom(:,im,iy) = Xw_mm(:,im,iy) - Xw_LT;
  end
end

%---multiply arrays by prefactors to get friendly units (mas for X1 and X2, ms for X3)

Xm = Xm_mm*0+NaN;
Xw = Xm_mm*0+NaN;

Xm(1:2,:,:) = rad2mas*pm12*Xm_mm_anom(1:2,:,:);
Xw(1:2,:,:) = rad2mas*pw12*Xw_mm_anom(1:2,:,:);
Xm(3,:,:) = LOD0*pm3*Xm_mm_anom(3,:,:);
Xw(3,:,:) = LOD0*pw3*Xw_mm_anom(3,:,:);

%---plot 12-month cycles for 6 aam terms, all years

LW = 3;
ifig = 1;
TTw = {'\chi_1 Wind Term','\chi_2 Wind Term','\Delta LOD Wind Term'};
TTm = {'\chi_1 Mass Term','\chi_2 Mass Term','\Delta LOD Mass Term'};
TTt = {'\chi_1 Total','\chi_2 Total','\Delta LOD Total'};

col = rand(nyears,3);
lh = zeros(2,1);

X = zeros(3,3,nm,nyears);
X(1,:,:,:) = Xw;
X(2,:,:,:) = Xm;
X(3,:,:,:) = Xw+Xm;

Xmean =  zeros(3,3,nm);
for im = 1:nm
  dum_w = squeeze(X(1,1,im,:));
  dum_m = squeeze(X(2,1,im,:));
  dum_w = squeeze(X(1,1,im,:));
  good_years_w = find(isfinite(dum_w) == 1);
  good_years_m = find(isfinite(dum_m) == 1);
  Xmean(1,:,im) = mean(X(1,:,im,good_years_w),4);
  Xmean(2,:,im) = mean(X(2,:,im,good_years_m),4);
end


% pre-defined y-axes for these plots.
ax = zeros(3,2);
ax(1,:) = 60*[-1,1];	% range for X1 in mas
ax(2,:) = 60*[-1,1];	% range for X2 in mas
ax(3,:) = [-1,1];	% range for DLOD in ms

for ii = 1:3	% loop over terms: X1, X2, LOD

  figure(ii+6), clf

  for jj = 1:2      % loop over components of each AAM term (w, m, total)
    subplot(1,3,jj)
    for iy = 1:nyears
      lh(1) = plot(1:12,squeeze(X(jj,ii,:,iy)),'Color',0.7*ones(3,1),'LineWidth',LW);
      hold on
    end
    dum = squeeze(X(jj,ii,:,:));
    [a,b,c] = find(isfinite(dum) == 1);
    lh(2)= plot(1:nm,squeeze(Xmean(jj,ii,:)),'k-','LineWidth',LW);
    axis([0 12 ax(ii,:)]);
    xlabel('Month')
    if ii < 3, ylabel('mas'), else ylabel('ms'), end
    legend(lh,'Years','Mean')
    if jj == 1, title(TTw(ii)), end
    if jj == 2, title(TTm(ii)), end
  end
  
  subplot(1,3,3)
  lh2 = zeros(1,3);
  lh2(1) = plot(1:nm,squeeze(Xmean(1,ii,:)),'k-','LineWidth',LW);
  hold on
  lh2(2) = plot(1:nm,squeeze(Xmean(2,ii,:)),'k--','LineWidth',LW);
  lh2(3) = plot(1:nm,squeeze(Xmean(1,ii,:))+squeeze(Xmean(2,ii,:)),'r-','LineWidth',LW);
  axis([0 12 ax(ii,:)]);
  legend(lh2,'wind term','mass term','total') 
  xlabel('Month')
  if ii < 3, ylabel('mas'), else ylabel('ms'), end
  title(TTt(ii))

end



